version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: gmeet-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - gmeet-network

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: gmeet-backend
    restart: unless-stopped
    environment:
      DATABASE_URL: "postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}?schema=public"
      PORT: ${PORT}
    ports:
      - "${PORT}:${PORT}"
    depends_on:
      - postgres
    networks:
      - gmeet-network
    command: >
      sh -c "npx prisma migrate deploy &&
             npm run start:prod"

volumes:
  postgres_data:

networks:
  gmeet-network:
    driver: bridge
